# Production Docker Compose Configuration
# Before running: cp .env.prod.example .env.prod and configure your values

services:
  # Production Frontend with Nginx
  frontend:
    image: swczk/pulveriza-nenem-frontend:latest
    container_name: spray-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - spring-api
      - graphql-api
    networks:
      - spray-network
    restart: always

  # Spring Boot API
  spring-api:
    image: swczk/pulveriza-nenem-spring-api:latest
    container_name: spray-spring-api-prod
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION}
      AWS_COGNITO_URL: ${AWS_COGNITO_URL}
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_CLIENT_SECRET: ${AWS_COGNITO_CLIENT_SECRET}
    networks:
      - spray-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  # GraphQL API
  graphql-api:
    image: swczk/pulveriza-nenem-graphql-api:latest
    container_name: spray-graphql-api-prod
    environment:
      MONGO_URI: mongodb://admin:${MONGO_PASSWORD:-password}@mongodb:27017
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: 8080
    networks:
      - spray-network
    restart: always
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: spray-mongodb-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db
      - ./backend-graphql/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - spray-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  mongodb_data:
    driver: local

networks:
  spray-network:
    driver: bridge

# Load environment variables from .env.prod file
# Create .env.prod from .env.prod.example and configure your values
